# -*- coding: utf-8 -*-
"""matheuskoren_135435_algoritmos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yo4ln1ekRRifL-m2LdznlSSn8i8bk4bW
"""

while True:
    try:
        n1 = float(input("QUAL FOI A SUA PRIMEIRA NOTA? "))
        n2 = float(input("QUAL FOI A SUA SEGUNDA NOTA? "))
        n3 = float(input("QUAL FOI A SUA TERCEIRA NOTA? "))

        if 0 <= n1 <= 10 and 0 <= n2 <= 10 and 0 <= n3 <= 10:
            break
        else:
            print("Por favor, insira notas válidas entre 0 e 10.")

    except ValueError:
        print("Por favor, insira notas válidas como números.")

# Calculando a média ponderada
p1 = 2
p2 = 3
p3 = 5

media_ponderada = ((n1 * p1) + (n2 * p2) + (n3 * p3)) / (p1 + p2 + p3)

# Verificando se o aluno foi aprovado ou precisa de recuperação
if media_ponderada < 7:
    print("Infelizmente você ficou de recuperação na disciplina de Algoritmos Computacionais, com uma média de:", media_ponderada)
else:
    print("Parabéns! Você está aprovado na disciplina de Algoritmos Computacionais, e sua média final é:", media_ponderada)